### ISSUE TITLE
rebuild for EL 7.8

### ISSUE THREAD

**Issue by sterndata** [iusrepo/php73-pecl-imagick#1]
Error: Package: php73-pecl-imagick-3.4.4-2.el7.ius.x86_64 (@ius-testing)
           Requires: libMagickCore.so.5()(64bit)
           Removing: ImageMagick-6.7.8.9-18.el7.x86_64 (@cr)
               libMagickCore.so.5()(64bit)
           Updated By: ImageMagick-6.9.10.68-3.el7.x86_64 (cr)
               Not found

**Comment by carlwgeorge** [comment]
This is due to RHEL 7.8 rebasing the ImageMagick library to a newer version.  The IUS *-pecl-imagick packages need to be rebuilt against that new library.  You're seeing the same error on CentOS because the CentOS CR repo contains packages from their upcoming 7.8 equivalent.  To workaround it for now, you can disable the CR repo to get it to install, or exclude ImageMagick from your upgrade command.  I'll take care of the rebuilds soon, and they will be available in ius-testing until the CentOS 7.8 rebuild is released.

**Comment by carlwgeorge** [comment]
This has been resolved in php73-pecl-imagick-3.4.4-3, which is currently available from the ius-testing repo.

```
yum --enablerepo ius-testing update php73-pecl-imagick
```

I plan to leave it there until the CentOS rebuild of 7.8 is released.

**Comment by carlwgeorge** [comment]
CentOS 7.8 has been released, and thus this has been promoted to the main repository.
